"""empty message

Revision ID: 845bf14f5e40
Revises: c0d1d088e73e
Create Date: 2021-08-28 20:09:33.407631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845bf14f5e40'
down_revision = 'c0d1d088e73e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.VARCHAR(), nullable=False),
    sa.Column('cif', sa.VARCHAR(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cif')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nick', sa.VARCHAR(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nick')
    )
    op.add_column('account', sa.Column('is_client', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'is_client')
    op.drop_table('client')
    op.drop_table('business')
    # ### end Alembic commands ###
